[versions]
kotlin = "2.2.10"
androidGradlePlugin = "8.12.1"
composeMultiplatform = "1.8.2"

# compose-app module's configuration information
composeApp-group = "legalbot.compose.app"
composeApp-version = "1.0.0"

# compose-app module's android library configuration information
composeApp-androidLibrary-namespace = "legalbot.compose.app"
composeApp-androidLibrary-compileSdk = "36"
composeApp-androidLibrary-minSdk = "24"

[libraries]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }